version: "3"
services:
    serve-sql:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${SCENARIO_DBPWD}
            MYSQL_ROOT_HOST:  ${DBROOT}
        ports:
            - 3306:3306
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        
    serve-location:
        restart: always
        image: location-app
        container_name: main-service
        hostname: main-service
        network_mode: "host"
        environment:
            SCENARIO_DBHOST: ${SCENARIO_DBHOST}
            SCENARIO_DBNAME: ${SCENARIO_DBNAME}
            SCENARIO_DBPWD: ${SCENARIO_DBPWD}
            SCENARIO_DBPPORT: ${SCENARIO_DBPPORT}
        ports:
            - "3010:3010"
        depends_on:
            - serve-sql
               

     